### PR TITLE
Add video to production framework

### PR DESCRIPTION
**Pull request by brikis98**
The video for my talk [Cloud Adoption Fails: 5 Ways Deployments Go Wrong and 5 Solutions](https://www.youtube.com/watch?v=sYzhlBayRpU) is now available. Since this talk introduces the Gruntwork Production Framework, I'm embedding the video in the guide.

Direct link to relevant page in preview env: https://deploy-preview-449--pensive-meitner-faaeee.netlify.app/guides/production-framework/

### CODE REVIEW

**Comment by brikis98** [comment]
How come the Netlify preview didn't seem to update after my latest commit?

**Comment by brikis98** [comment]
Ah, whoops, I think I updated the wrong file 🤦

**Comment by brikis98** [comment]
Hm, or not... The preview still seems to be showing the first commit?

**Comment by brikis98** [comment]
@eak12913 @oredavids What am I missing?

**Review by rhoboat — DISMISSED** [review]
LGTM!

**Comment by brikis98** [comment]
For clarity: the preview URL shows the video, but it isn’t 100% width and the text above it isn’t up to date… I added the video in one commit, then did the 100% width & text changes in subsequent commits, but the preview only shows the first commit.

**Comment by rhoboat** [comment]
Going to try kicking off the job again. I think we recreated the mistakenly deleted `client-gruntwork` team.

**Comment by yorinasub17** [comment]
> For clarity: the preview URL shows the video, but it isn’t 100% width and the text above it isn’t up to date… I added the video in one commit, then did the 100% width & text changes in subsequent commits, but the preview only shows the first commit.

Looks like you introduced an error in this commit. From the netlify build log:

```
10:01:06 AM: [ERROR] Docusaurus Node/SSR could not render static page with path /guides/production-framework/ because of following error:
10:01:06 AM: Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
10:01:06 AM:     at a.b.renderDOM (main:86857:354)
10:01:06 AM:     at a.b.render (main:86852:399)
10:01:06 AM:     at a.b.read (main:86851:83)
10:01:06 AM:     at Object.exports.renderToString (main:86862:138)
10:01:06 AM:     at doRender (main:22891:356)
10:01:06 AM:     at async serverEntry_render (main:22887:284)
10:01:10 AM: [success] [webpackbar] Server: Compiled with some errors in 16.85s
10:01:10 AM: Error: Server-side rendering fails due to the error above.
10:01:10 AM: [ERROR] Unable to build website for locale en.
10:01:10 AM: [ERROR] Error: Failed to compile with errors.
10:01:10 AM:     at /opt/build/repo/node_modules/@docusaurus/core/lib/webpack/utils.js:202:24
10:01:10 AM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:554:14
10:01:10 AM:     at processQueueWorker (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:491:6)
10:01:10 AM:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
10:01:10 AM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
```

**Comment by brikis98** [comment]
> > For clarity: the preview URL shows the video, but it isn’t 100% width and the text above it isn’t up to date… I added the video in one commit, then did the 100% width & text changes in subsequent commits, but the preview only shows the first commit.
> 
> Looks like you introduced an error in this commit. From the netlify build log:
> 
> ```
> 10:01:06 AM: [ERROR] Docusaurus Node/SSR could not render static page with path /guides/production-framework/ because of following error:
> 10:01:06 AM: Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
> 10:01:06 AM:     at a.b.renderDOM (main:86857:354)
> 10:01:06 AM:     at a.b.render (main:86852:399)
> 10:01:06 AM:     at a.b.read (main:86851:83)
> 10:01:06 AM:     at Object.exports.renderToString (main:86862:138)
> 10:01:06 AM:     at doRender (main:22891:356)
> 10:01:06 AM:     at async serverEntry_render (main:22887:284)
> 10:01:10 AM: [success] [webpackbar] Server: Compiled with some errors in 16.85s
> 10:01:10 AM: Error: Server-side rendering fails due to the error above.
> 10:01:10 AM: [ERROR] Unable to build website for locale en.
> 10:01:10 AM: [ERROR] Error: Failed to compile with errors.
> 10:01:10 AM:     at /opt/build/repo/node_modules/@docusaurus/core/lib/webpack/utils.js:202:24
> 10:01:10 AM:     at /opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:554:14
> 10:01:10 AM:     at processQueueWorker (/opt/build/repo/node_modules/webpack/lib/MultiCompiler.js:491:6)
> 10:01:10 AM:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
> 10:01:10 AM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
> ```
> 
> And the actual error message:
> 
> > The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.

Ohhh, man, I totally missed that. I tried browsing the logs, but I think I was still seeing the logs from the old preview env and not the new (broken) one 🤦 

Thanks for the pointer!

**Comment by brikis98** [comment]
OK, I had to use JSX syntax, and now things are working. Thanks for the eagle eyes @yorinasub17!

I need one more "ship it" and this is good to go!

**Review by yorinasub17 — APPROVED** [review]
LGTM!

**Comment by rhoboat** [comment]
@yorinasub17 Where did you see the "actual error message"?

**Review by rhoboat — APPROVED** [review]
LGTM!

image

**Comment by yorinasub17** [comment]
> Where did you see the "actual error message"?

It's in the link in the error message in the deploy logs.

**Comment by rhoboat** [comment]
Sorry, but which link? I'm just not seeing what you're seeing.

I only see these kind of informational links:
https://reactjs.org/docs/error-decoder.html?invariant=62
https://ntl.fyi/exit-code-1

**Comment by brikis98** [comment]
Thank you for the review! Merging and releasing now.

**Pull request merged**
