### PR TITLE
[APT-1554] Configure docs for google search

### PR DESCRIPTION
**Pull request by oredavids**
#### What does this PR do?
- Updates to docusaurus version 2-beta-14
- Fixes meta title for home page
- Removes unnecessary pages

[APT-1554]

[APT-1554]: https://gruntwork.atlassian.net/browse/APT-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ebeneliason — APPROVED** [review]
LGTM.

**Comment by ebeneliason** [comment]
Oh, one thing to look out for is whether any changes were made to components that we've swizzled (`TOCItem`, `Toggle`). I'm not sure if there's any mechanism in place to automatically detect this and suggest changes. I'm also not sure if there's any best practice way to apply our changes to a "re-swizzled" component. Thoughts?

**Comment by oredavids** [comment]
@ebeneliason

I checked the release notes for TOCItem originally and there haven't been any updates to that component in any new release after our current version.

I have now seen an update for the Toggle component which is swizzled in your PR #120. We could wait till this PR is merged to re-swizzle that component because it was simplified in [v2-beta-10](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.10)- it is categorized as a polish so it is not a breaking change so waiting & re-doing the PR is not necessary.

Generally, I could not find any mechanism in place to automatically detect/suggest changes to swizzled components and that is somewhat understandable given that [Docusaurus does not recommend sizzling](https://docusaurus.io/docs/using-themes#swizzling-theme-components) while they are still in the beta phase. We will have to keep checking release notes before any future upgrades.

**Comment by ebeneliason** [comment]
> I have now seen an update for the Toggle component which is swizzled in your PR #120. We could wait till this PR is merged to re-swizzle that component…

That sounds like a plan. Feel free to merge this when ready!

**Pull request merged**
