### PR TITLE
[APT-1628] Fix icons for theme toggle switch

### PR DESCRIPTION
**Pull request by ebeneliason**
These were applied with styles that should have been associated with the
module. We now swizzle the Toggle component to adjust the behavior.

### CODE REVIEW

**Review by oredavids — APPROVED** [review]
LGTM.

**Comment by ebeneliason** [comment]
We need to wait to re-swizzle this once #123 is merged.

**Comment by oredavids** [comment]
#123 now merged.

**Comment by ebeneliason** [comment]
> We need to wait to re-swizzle this once #123 is merged.

I tried rebasing on the latest master which includes the Docusaurus upgrade, and re-swizzling the `Toggle` component. The resulting diff, after adding back in the custom CSS we added, is empty. As such, I think there's nothing else to do here and we can merge this as is. @oredavids Any hesitation?

**Comment by oredavids** [comment]
@ebeneliason that's curious but I don't have any hesitation given the supposed improvements were meant to be a polish. Perhaps it was in a dependency.

**Comment by ebeneliason** [comment]
Oops — I just failed to run `yarn` to update locally before swizzling. I'll push a commit with the change in a moment.

**Comment by ebeneliason** [comment]
Ready for re-review.

**Review by oredavids — APPROVED** [review]
LGTM.

**Pull request merged**
