### PR TITLE
Update new account guide

### PR DESCRIPTION
**Pull request by jbrooks-sms**
Updated the instructions to include copying the ops-admin-role to the new account being created and added instructions to add a CIDR for the mgmt vpc in the common.hcl file

### CODE REVIEW

**Comment by oredavids** [comment]
Thank you @jbrooks-sms. We'll get this queued up for review.

**Comment by josh-padnick** [comment]
@eak12913 This change was made prior to our docs site re-org. Still, this content is still available. Any issue with merging this?

**Comment by MoonMoon1919** [comment]
@josh-padnick This content was removed yesterday and now redirects to the new refarch docs.

@jbrooks-sms Thanks for the contribution! We recently redesigned our docs site and have refactored our reference architecture docs. The new content can be found here: https://docs.gruntwork.io/refarch/usage/maintain-your-refarch/adding-new-account#deploy-the-security-baseline-for-the-app-account. Could you kindly check the new docs and see if that sufficiently serves your needs?

Thanks in advance!

**Comment by MoonMoon1919** [comment]
Closing this PR as there has not been activity in over a month.

**Pull request closed without merging**
