### PR TITLE
Add Gruntwork Favicon

### PR DESCRIPTION
**Pull request by robmorgan**
This PR adds a Gruntwork Favicon.

### CODE REVIEW

**Comment by robmorgan** [comment]
Screenshot 2019-05-27 10 06 46
Screenshot 2019-05-27 10 06 54

Can hardly see the 1px border I did on the white up-state

**Comment by yorinasub17** [comment]
Any objections to merging @robmorgan ?

**Comment by yorinasub17** [comment]
Ok going to merge this since I can't live another day seeing that purple G.

**Comment by robmorgan** [comment]
@yorinasub17 best move. We can always update later, better to have something 👍

**Pull request merged**
