### PR TITLE
Update releases through end of Feb

### PR DESCRIPTION
**Pull request by brikis98**
Ran `docs-sourcer`.

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Hm, looks like we have a bug.

The 2023-02 link did not get added to https://deploy-preview-663--pensive-meitner-faaeee.netlify.app/guides/stay-up-to-date/. It did get added to https://deploy-preview-663--pensive-meitner-faaeee.netlify.app/guides/stay-up-to-date/releases/. 

So I'm guessing the placeholder on the Stay Up To Date page must have been overwritten by someone?

**Comment by brikis98** [comment]
Yup... There it is: https://github.com/gruntwork-io/docs/pull/651/files#diff-2c48f0abe300a4f86d96845d63009658523ac90f621f541ea224e76a4a0d7095L19

@marinalimeira or @robmorgan Could you please put that placeholder back?

**Comment by eak12913** [comment]
I put up #667 to revert the immediate issue. I have also spoken about this with @oredavids and I will file a JIRA ticket to address the underlying problem that's causing the team grief in this area.

**Comment by eak12913** [comment]
🤔 Something must still be off as I'm seeing:

image

@oredavids, as I'll be out all next week, could you please assist Jim to make sure this ships?

**Comment by eak12913** [comment]
Yea - it generated the new month in [one of the pages](https://deploy-preview-663--pensive-meitner-faaeee.netlify.app/guides/stay-up-to-date/releases/) but not in the but not on [this page](https://deploy-preview-663--pensive-meitner-faaeee.netlify.app/guides/stay-up-to-date/). You can even see that the page still has the `<!--....this will be replaced...-->` comment in it.

**Comment by oredavids** [comment]
The merge in #667 to master fixed one problem and introduced another by deleting the releases section of stay-up-to-date page. [Details](https://github.com/gruntwork-io/docs/pull/667#discussion_r1125601845).

The fix was achieved by re-running the docs-sourcer's release-plugin for february which resulted in only the deleted sections being correctly replaced. See [commit](https://github.com/gruntwork-io/docs/pull/663/commits/654d9787ccf8c938def1edec6e5a4e9296d9d056).

The February releases now correctly show up on the main stay-up-to-date page and the releases page:
- https://deploy-preview-663--pensive-meitner-faaeee.netlify.app/guides/stay-up-to-date/
- https://deploy-preview-663--pensive-meitner-faaeee.netlify.app/guides/stay-up-to-date/releases

@brikis98 this can be merged now.

Screenshot 2023-03-04 at 11 10 09 PM

**Comment by brikis98** [comment]
Thank you @eak12913 and @oredavids for getting this done!

**Pull request merged**
