### PR TITLE
Add a new support page

### PR DESCRIPTION
**Pull request by ebeneliason**
In addition to adding the content for the page itself, this change
removes the link from the Guides section sidebar, but adds it to
the footer. (It's also already linked to from the header nav.)

### CODE REVIEW

**Comment by ebeneliason** [comment]
This PR still needs final content for the Pro Serve section at the bottom, but is otherwise ready for review.

**Review by brikis98 — COMMENTED** [review]
I found this page a bit hard to navigate. I imagine if a customer clicks "Support" and really needs help, they don't want to read long paragraphs of text, info about upsells, etc. I think what they want is a quick pointer to get help. Something like:

- Ask a question: GitHub Discussions
- Ask a question privately: support@gruntwork.io
- Ask an urgent question: urgent-support@gruntwork.io
- Disclose a security vulnerability: security@gruntwork.io
- Report a bug: GitHub Issues
- Request a feature: GitHub Issues
- Contribute an improvement: GitHub PR
- Work live with Gruntwork engineers: Pro Serve

And then for each of those, we can provide more info below... But that list of quick pointers at the top seems really important. WDYT?

**Comment by eak12913** [comment]
Jim's points make good sense! Seems like they can be included in an "info" block at the top as a "tldr;" of sorts. The rest of the content does a good job describing the different support offerings. It seems best suited for educating someone who _is not_ yet a subscriber. Relevant for sure but better below the "tldr;" section.

**Comment by ebeneliason** [comment]
>  if a customer clicks "Support" and really needs help, they don't want to read long paragraphs of text

Agreed. What this first iteration of the page doesn't reflect is the intention to represent the main CTAs as large clickable cards. Here's what that's intended to look like. (I've made very quick progress towards this, so I'll likely push it as an update to this PR instead of needing a follow-up.)

image

> I think what they want is a quick pointer to get help.

This is the direction I'm leading with the cards, and we can certainly add more of them. We can also rephrase them to reflect goals instead of resources (e.g. "Ask a Question" instead of "Knowledge Base." However, I didn't include things like "Email us" there because I didn't want to misrepresent what support resources are available to someone, and the docs site presently has no knowledge of a user's subscription. Specifically, my understanding is that basic support doesn't include email support. That said, we could use the same card treatment for the "How to reach us" sections for pro/enterprise, so they jump out more readily on the page.

> Ask an urgent question: urgent-support@gruntwork.io

I was unaware of this. Is this a support avenue we already offer? Under which plan(s)?

> Report a bug: GitHub Issues
> Request a feature: GitHub Issues
> Contribute an improvement: GitHub PR

I wasn't sure what to do with the current "File a Bug" card, given that we can't link to the appropriate repo. Right now I just link to the GitHub repos list. This would affect all three of these items. Should we continue linking to a general GitHub page, or should these be purely instructional instead?

**Comment by ebeneliason** [comment]
> I didn't want to misrepresent what support resources are available to someone, and the docs site presently has no knowledge of a user's subscription.

Responding to my own previous comment…another potential solution is to use a "tag" treatment to identify which tier of support is required for each card. In that model, we could drop the "Community Support" Header (or replace with e.g. "Quick Support Links"), enumerate all options across all tiers, and add pill-shaped or rounded rect `basic`, `professional`, and `enterprise` tags somewhere within the card itself. I'll explore what that might look like.

**Comment by ebeneliason** [comment]
I've pushed the card grid update. The icon color isn't dynamic with the theme yet, so right now they look a little better in light mode (switch, top right). Here's a mockup of how tagged cards could look, exposing more support avenues up front. I think this works pretty well.
image

**Review by oredavids — APPROVED** [review]
Looks good to me - since other improvements will be made in a follow up PR as you've mentioned. I would suggest additional white space between the  "Community Resources" & "Paid Support Tier".

**Comment by ebeneliason** [comment]
I'm going to go ahead and merge this PR so we have a baseline, but I'll leave the story open so we can incorporate additional feedback and iterate further on the cards we display. @brikis98 Feel free to provide follow-up comments here even after it's closed, or drop a comment in #team-platform. You'll be able to preview the cards live at https://docs.dogfood-stage.com once merged.

**Comment by brikis98** [comment]
> > if a customer clicks "Support" and really needs help, they don't want to read long paragraphs of text
> 
> Agreed. What this first iteration of the page doesn't reflect is the intention to represent the main CTAs as large clickable cards. Here's what that's intended to look like. (I've made very quick progress towards this, so I'll likely push it as an update to this PR instead of needing a follow-up.)
> 
> image
> 

Using cards seems like a great approach!

> > Ask an urgent question: [urgent-support@gruntwork.io](mailto:urgent-support@gruntwork.io)
> 
> I was unaware of this. Is this a support avenue we already offer? Under which plan(s)?

[One of our insights for the new product direction](https://www.notion.so/gruntwork/Roll-out-plan-61ff1e625e344120aff68d7f2284fab8#0d536d78201345ccb90f8b29b3df14bf) is that we want to replace Slack support with (a) a docs site, (b) knowledge base, (c) Pro Serve, and (d) urgent support. We haven't gotten to urgent support yet, but should probably start thinking through it soon. CC @josh-padnick @marijakstrazdas 

> 
> > Report a bug: GitHub Issues
> > Request a feature: GitHub Issues
> > Contribute an improvement: GitHub PR
> 
> I wasn't sure what to do with the current "File a Bug" card, given that we can't link to the appropriate repo. Right now I just link to the GitHub repos list. This would affect all three of these items. Should we continue linking to a general GitHub page, or should these be purely instructional instead?

Perhaps purely instructional? Or link to another spot on the page with detailed instructions? And/or list of repos?

**Pull request merged**
